### ISSUE TITLE
Project: MOC Proof-of-Concept

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#105]
## Purpose
- Deploy containerized Dataverse on Mass Open Cloud to support large data and computing
- Present demo of proof-of-concept at the [Mass Open Cloud Alliance Conference](https://massopen.cloud/2024-workshop/) on 2024/02/28

## Background
- [Mass Open Cloud Alliance](https://massopen.cloud/) is a "partnership between higher education, medical research centers, government, and industry provides structure and resources that enable a close collaboration between research, development, and operations in a series of interconnected projects."
- The MOC team wants to test a containerized Dataverse installation on the MOC infrastructure to support large data and computing.

## Participants
- Leonid Andreev, @landreev 
- Gustavo Durand, @scolapasta 
- Sonia Barbosa, @sbarbosadataverse 
- Ceilyn Boyd, @cmbz 
- Stefano Iacus, @siacus 
- Max Shad
- James Culbert
- Milson Munakami
- Jim Myers, @qqmyers 
- Milan Kupcevic

## Timeline
- Start: 2024/01/08
  - Milestone: Deliver containerized Dataverse installation (2024/01/15)
  - Milestone: Binder equivalent functionality implemented (2024/01/31)
  - Upload presentation (2024/02/23)
  - **Milestone: Presentation (2024/02/24)**
  - Close out tasks
- End: 2024/04/01

## Tasks
- [x] Create NERC project (@siacus)
- [x] Project management: @cmbz and @scolapasta and @siacus coordinate re. resource allocation
  - [x] Assemble team
  - [x] GEOS-CHEM use case (see https://github.com/IQSS/dataverse-pm/issues/154)
  - [x] Set up recurring meetings, if needed (Slack channel used instead: https://iqss.slack.com/archives/C06EXB41EE5)
- [x] Set up Dataverse container/installation for MOC (DevOps, @landreev)
- [x] Arrange for authentication support for Keycloak
- [x] Move from Binder to local NERC infrastructure to run workflows (Development, @pdurbin)
- [x] Arrange for support of NESE tape connection
- [x] Finalize presentation (@siacus)

## Issues
- [x] https://github.com/IQSS/dataverse-pm/issues/172

## Related
- https://github.com/IQSS/dataverse-pm/issues/119
- https://github.com/IQSS/dataverse-pm/issues/106
- https://github.com/IQSS/dataverse-pm/issues/154
- https://github.com/IQSS/dataverse/issues/10238
- https://github.com/IQSS/dataverse/issues/10302

## Technical Resources
- [x] NESE tape resources
- [x] NESE disk resources

## Project Resources
- [Google Drive Folder](https://drive.google.com/drive/folders/1bDmxDSylZRtLDdks7ZQVOEr2WaO4kRJe?usp=drive_link)
- [Running Meeting Notes](https://docs.google.com/document/d/1X2mLE6Z1nOpyP9WZYGjFez0i8E_Gm3zqEWKKfqTMrXQ/edit?usp=drive_link)
- [Slack Channel](https://iqss.slack.com/archives/C06EXB41EE5)
- [Presentation Slides](https://docs.google.com/presentation/d/19DAVXV16eW78yx5hKjN01YyFi9mR4s3DBnwNHwBelGI/edit#slide=id.g2b264cf6ddb_0_0)

**Comment by cmbz** [comment]
2024/01/29: Updated with new task: https://github.com/IQSS/dataverse-pm/issues/172

**Comment by landreev** [comment]
A possible dependency: IQSS/dataverse#10302. 
I can make a PR very quickly if/when needed.

**Comment by landreev** [comment]
edited the checklist to add the NESE tape volume.

**Comment by landreev** [comment]
Marked the "NESE tape" item as complete on the checklist - under the assumption that it is complete "for the purposes of the MOC PoC presentation slides". I'm opening a new issue dedicated to figuring out a working setup, with a functioning Borealis app hosted on the server, etc., that can be used by real users, that we can later replicate in IQSS prod.

**Comment by cmbz** [comment]
2024/03/01
- Closing issue as complete
- See follow up: https://github.com/IQSS/dataverse-pm/issues/184
