### ISSUE TITLE
Epic: GREI 5 - Use Cases

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#119]
## Overview
"Implement generalist repository use cases, cross repository use cases, and community imputed use cases."

### GREI
- [x] https://github.com/IQSS/dataverse-pm/issues/140
- [x] https://github.com/IQSS/dataverse-pm/issues/141
- [x] https://github.com/IQSS/dataverse-pm/issues/142

#### Large Data Support
- https://github.com/IQSS/dataverse-pm/issues/176
  - https://github.com/IQSS/dataverse-HDV-Curation/issues/344
- https://github.com/IQSS/dataverse-pm/issues/106 (included #269)
- #254
- #255

#### Indigenous Data Support
- https://github.com/IQSS/dataverse-pm/issues/170

#### Email as a Research Object Support
- #266

## Related
- https://github.com/IQSS/dataverse-pm/issues/197
- https://github.com/IQSS/dataverse-pm/issues/327

## Resources
- https://github.com/IQSS/dataverse-pm/issues/370
- https://github.com/IQSS/dataverse-pm/issues/124
- [APPROVED - NIH GREI Coopetition Plan Year 3](https://docs.google.com/document/d/1XTJSOfUlg06WYGXe3URVFH6VaPMkBNPqVZgrsqOrbc0/edit?usp=sharing)

**Comment by cmbz** [comment]
## Status: June 2024
- https://github.com/IQSS/dataverse-pm/issues/106 is closed. 
- Work continues here: https://github.com/IQSS/dataverse-pm/issues/268

**Comment by cmbz** [comment]
## Status: Year 3, Q1
- The team made significant progress toward supporting large data for Harvard Dataverse. The Dataverse Large Data Working group was established, several projects joined the large data support pilot, and refinements were made to user- and internal-facing services documentation was prepared. To support indigenous data, stakeholders met to review the proposed integration of TKlabels with DV: [TKLabels: Design Options for Integrating with Dataverse](https://docs.google.com/document/d/1umSncPhXApNcvstzqMbqIfx87LCB3RqwS69gPCvbDVE/edit?pli=1#heading=h.w5gbovoa191i) and initiated plans to join the [TK Labels Service Provider Early Adopter Program](https://localcontexts.org/service-provider-early-adopter-program/).
- See: [NIH GREI Quarterly Progress Report: Year3 Q1 (March 2024 - May 2024)](https://docs.google.com/document/d/13YjLUaImTO-BfscD3l8kByQvKrZm-YJGxdMLgzzq4VU/edit?usp=sharing)

**Comment by cmbz** [comment]
## Status: Year 3, Q2
- Pending

**Comment by cmbz** [comment]
## Status: Year 3, Q3
- Pending

**Comment by cmbz** [comment]
## Status: Year 3, Q4
- Pending

**Comment by cmbz** [comment]
## Status: Year 4, Q1
- Pending

**Comment by cmbz** [comment]
2026-03-13: We will continue this use case in Year 5: https://github.com/IQSS/dataverse-pm/issues/516
