### ISSUE TITLE
Project: NIH GREI - Generalist Repository Ecosystem Initiative, Year 3

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#124]
## Vision
The long-term vision for GREI is to develop collaborative approaches for data management and sharing through inclusion of the generalist repositories in the NIH data ecosystem. GREI also aims to better enable search and discovery of NIH-funded data in the generalist repositories.

## Mission
GREI’s mission is twofold. The primary mission is to establish a common set of cohesive and consistent capabilities, services, metrics, and social infrastructure across various generalist repositories. Secondarily, GREI will raise general awareness and help researchers to adopt FAIR principles to better share and reuse data.

See: [NIH GREI Announcement](https://datascience.nih.gov/data-ecosystem/generalist-repository-ecosystem-initiative)

## GREI Repositories and Participants

1. [Dryad](https://datadryad.org/stash)
2. [Zenodo](https://zenodo.org/)
3. [Dataverse Project](https://dataverse.org) (and [Harvard Dataverse](https://dataverse.harvard.edu))
4. [Mendeley Data](https://data.mendeley.com/)
5. [DataCite](https://datacite.org/)
6. [figshare](https://figshare.com)
7. [OSF](https://osf.io)
8. [Vivli](https://vivli.org/)

#### GREI
- [ ] https://github.com/IQSS/dataverse-pm/issues/115
- [ ] https://github.com/IQSS/dataverse-pm/issues/116
- [ ] https://github.com/IQSS/dataverse-pm/issues/117
- [ ] https://github.com/IQSS/dataverse-pm/issues/118
- [ ] https://github.com/IQSS/dataverse-pm/issues/119
- [ ] https://github.com/IQSS/dataverse-pm/issues/120
- [ ] https://github.com/IQSS/dataverse-pm/issues/121
- [ ] https://github.com/IQSS/dataverse-pm/issues/122

### Harvard 
- [ ] https://github.com/IQSS/dataverse-pm/issues/123
- [ ] https://github.com/IQSS/dataverse-pm/issues/234

### Active
- https://github.com/NIH-GREI/grei-pm/issues/120 (Julie Goldman; tracked in GREI repo) 
- [ ] https://github.com/IQSS/dataverse-pm/issues/206 (@sbarbosadataverse)
- [ ] #332 (@dliburd and @sbarbosadataverse)
  - Note: In September 2024, the following two Task Groups were merged to create this new Group:
    - https://github.com/IQSS/dataverse-pm/issues/221, and 
    - https://github.com/IQSS/dataverse-pm/issues/207
- [ ] https://github.com/IQSS/dataverse-pm/issues/347 (@cmbz and @sbarbosadataverse)
- [ ] https://github.com/IQSS/dataverse-pm/issues/345 (@sbarbosadataverse)
- [ ] https://github.com/IQSS/dataverse-pm/issues/346 (@sbarbosadataverse)
      (Note that QA/QC and #Sensitive Data were combined into one task group during Y3 face to face meeting).

### Completed
- [x] https://github.com/IQSS/dataverse-pm/issues/187 (@emily-katz) (Work is tracked in https://github.com/IQSS/dataverse-pm/issues/234)
- [x] https://github.com/IQSS/dataverse-pm/issues/185 (@jggautier)
- [x] https://github.com/IQSS/dataverse-pm/issues/186 (@sbarbosadataverse)
- [x] https://github.com/IQSS/dataverse-pm/issues/207 (@sbarbosadataverse)
- [x] https://github.com/IQSS/dataverse-pm/issues/221 (@dliburd)
- [x] https://github.com/IQSS/dataverse-pm/issues/222 (@scolapasta)

## Grant Supplements
- https://github.com/IQSS/dataverse-pm/issues/234

## Reports
- [x] https://github.com/IQSS/dataverse-pm/issues/191
- [ ] https://github.com/IQSS/dataverse-pm/issues/188
- [ ] https://github.com/IQSS/dataverse-pm/issues/189
- [ ] https://github.com/IQSS/dataverse-pm/issues/190

## Timeline
- Start: February 2022
- End: February 2026

### GREI Program Resources
- https://github.com/NIH-GREI/grei-pm/issues/33 (monthly GREI updates)
- https://github.com/NIH-GREI/grei-pm/issues/16
- [APPROVED - NIH GREI Coopetition Plan Year 3](https://docs.google.com/document/d/1XTJSOfUlg06WYGXe3URVFH6VaPMkBNPqVZgrsqOrbc0/edit?usp=sharing)

### Harvard GREI Resources
- [GREI Status Dashboard - Year 3
](https://docs.google.com/spreadsheets/d/19MqI3II5dDJa6x8G2c8Giu29Z4XhzbWUN76tCAoMO58/edit?usp=sharing)
- [NIH OTA](https://docs.google.com/document/d/1cFK8pdwMKIRZxNs8EZXL1cXmW0ho6Rx9ulCewJ1ZCFI/edit?usp=sharing)
- [GREI Year 3 Planning spreadsheet](https://docs.google.com/spreadsheets/d/197SO3NvuTrwt7w3CgRGVTr6RFjVFTJt6LCeZAK7v-Ns/edit?usp=sharing)
- [Google Drive Folder](https://drive.google.com/drive/u/0/folders/0ACthvafpCn06Uk9PVA)
- [Monthly Status Reports](https://drive.google.com/drive/folders/11nQBFXKL3jGq8E2HLkcTWmcSu3xCupS8?usp=drive_link)
- [DRAFT: Year 3 Realignment Proposal Plan](https://docs.google.com/document/d/1ADskSIH6T4LGt8Lz4eibzNOq4lnzGNxu/edit?usp=drive_link&ouid=102516728224230315414&rtpof=true&sd=true) (approved)

**Comment by cmbz** [comment]
## January 2024 Updates
- https://github.com/IQSS/dataverse-pm/issues/174
- https://github.com/IQSS/dataverse-pm/issues/171
- https://github.com/IQSS/dataverse-pm/issues/176
- https://github.com/IQSS/dataverse-pm/issues/146
- https://github.com/IQSS/dataverse-pm/issues/123

**Comment by cmbz** [comment]
## February 2024 Updates
- https://github.com/IQSS/dataverse-pm/issues/171#issuecomment-1959671784
- https://github.com/IQSS/dataverse-pm/issues/123#issuecomment-1973718839
- https://github.com/IQSS/dataverse-pm/issues/176#issuecomment-1973960190
-

**Comment by cmbz** [comment]
## March 2024 Updates

- TBD

**Comment by cmbz** [comment]
## April 2024 Updates

**Comment by cmbz** [comment]
## Status: May 2024
- Pending

**Comment by cmbz** [comment]
## Status: June 2024
- Pending

**Comment by cmbz** [comment]
## Status: August 2024
- Pending

**Comment by cmbz** [comment]
## Status: September 2024
- Pending

### Reports
- https://github.com/IQSS/dataverse-pm/issues/281

**Comment by cmbz** [comment]
## Status: October 2024
### GREI Objectives
#### GREI 1
#### GREI 2
#### GREI 3
#### GREI 4
#### GREI 5
#### GREI 6
#### GREI 7
#### GREI 8
#### GREI Re-arch

### Task Groups

**Comment by cmbz** [comment]
## Status: November 2024
### GREI Objectives
#### GREI 1
#### GREI 2
#### GREI 3
#### GREI 4
#### GREI 5
#### GREI 6
#### GREI 7
#### GREI 8
#### GREI Re-arch

### Task Groups

## Reports

**Comment by cmbz** [comment]
## Status: December 2024
### GREI Objectives
#### GREI 1
#### GREI 2
#### GREI 3
#### GREI 4
#### GREI 5
#### GREI 6
#### GREI 7
#### GREI 8
#### GREI Re-arch

### Task Groups

### Reports

**Comment by jggautier** [comment]
Hi @cmbz. About October 2024 updates for GREI 1 objectives, I'm not really involved in this objective. In the GitHub issue,  "Conduct a comprehensive internal review of the Generalist Repository Comparison Chart to improve clarity, transparency, and usability" [I read](https://github.com/IQSS/dataverse-pm/issues/125#issuecomment-2374080484) that a survey is planned to be sent out in early October. @sbarbosadataverse definitely knows more.

**Comment by cmbz** [comment]
@jggautier [Yes, thanks. I was aware of the survey](https://github.com/IQSS/dataverse-pm/issues/124#issuecomment-2448013214). But I didn't see a message on the GREI Slack that indicated it had gone out.

**Comment by cmbz** [comment]
## Status: January 2025
- Pending

**Comment by cmbz** [comment]
## Status: February 2025
- Pending

**Comment by cmbz** [comment]
2025-03-04
- GREI Year 3 is complete
- Follow Year 4 here: https://github.com/IQSS/dataverse-pm/issues/370
