### ISSUE TITLE
GREI 2: Implement the GREI Metadata Recommendations V1 and V2 for Harvard Dataverse

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#127]
## Overview
- This issue consolidates GREI 2 Task 1 and GREI 2 Task 2 work from Year 3 and Year 4.

## Issues

Year 5

- [x] 2.1 Task: GREI repositories complete [GREI Metadata Recommendation](https://doi.org/10.5281/zenodo.8101956) (version 1) implementation
  - [x] 2.1.1 Deliverable: Individual Repository Implementation of GREI Metadata Recommendation (version 1) 

  <details>
  <summary>Progress Towards GREI Metadata Recommendations (v1)</summary>

  | DataCite ID Category | # of properties | # of properties HDV  plans to "support" | # of properties HDV "supports" |
  |------------------------|-----------------------|-----------------------------------------------|----------------------------------------|
  | 2 Creator              | 11                    | 11                                            |11                                      |
  | 6 Subject              | 4                     | 4                                             | 4                                      |
  | 8 Date                 | 3                     | 2                                             | 2                                      |
  | 12 RelatedIdentifier   | 4                     | 4                                             | 4                                      |
  | 15 Version             | 1                     | 1                                             | 1                                      |
  | 16 Rights              | 5                     | 5                                             | 5                                      |
  | 17 Description         | 2                     | 2                                             | 2                                      |
  | 19 FundingReference    | 7                     | 5                                             | 5                                      |

  _For more details, [see "How does Harvard Dataverse follow NIH GREI’s metadata recommendations?"](https://docs.google.com/spreadsheets/d/1IbA_oLmilZ5Wugy6-Dx0EJX6gXdIqj7FrQKpXV1Wt_U) (Google Sheet)_
  </details>

- [x] 2.2 Task: Develop [GREI Metadata Recommendation (version 2)](https://docs.google.com/document/d/1xspBZoBzXpwo_p-tH1LpNfHGCWDEGo_HCo-QH27LvWc)
  - [x] 2.2.1 Deliverable: Publish Metadata Recommendation (V2) (https://doi.org/10.5281/zenodo.16953588)
- [ ] Ensure that we're able to keep in sync the repository's metadata, the metadata in the "Datacite" export, and the metadata we expect DataCite to have [#409](https://github.com/IQSS/dataverse.harvard.edu/issues/409)
- [ ] Continue evaluation of account page and deposit form redesigns for increasing ORCIDs and other ORCID-related recommendations in GREI Metadata Recommendations V2 ([#473](https://github.com/IQSS/dataverse-pm/issues/473))
- [ ] Review controlled vocabulary recommendations in GREI Metadata Recommendations V2 to determine next steps ([#474](https://github.com/IQSS/dataverse-pm/issues/474))
- [ ] Review use of Related Publication Relation Type field and alignment with related recommendations in GREI Metadata Recommendations V2 ([#472](https://github.com/IQSS/dataverse-pm/issues/472))
- [ ] Review date metadata in Harvard Dataverse and alignment with related recommendations in GREI Metadata Recommendations V2 ([#470](https://github.com/IQSS/dataverse-pm/issues/470))
- [ ] https://github.com/IQSS/dataverse-pm/issues/356
- [ ] https://github.com/IQSS/dataverse-pm/issues/409

<details>
<summary>Year 3 (metadata v1 recommendations)</summary>

#### UX Design and Testing
This work did not inform the software development of metadata v1 recommendations.
- https://github.com/IQSS/dataverse-pm/issues/275
- https://github.com/IQSS/dataverse-pm/issues/276
- https://github.com/IQSS/dataverse-pm/issues/258
- https://github.com/IQSS/dataverse-pm/issues/259
- https://github.com/IQSS/dataverse-pm/issues/260

#### Software Development
- https://github.com/IQSS/dataverse/issues/11075
- IQSS/dataverse-pm#224
- https://github.com/IQSS/dataverse/issues/5144
- https://github.com/IQSS/dataverse.harvard.edu/issues/326 (final v1 metadata issue)
</details>

## Related
- [Metadata recommendations from GREI Metadata and Search Subcommittee](https://doi.org/10.5281/zenodo.8101957)
- https://github.com/IQSS/dataverse.harvard.edu/issues/230
- https://github.com/IQSS/dataverse/issues/6640

## Resources
- https://github.com/IQSS/dataverse-pm/issues/370
- https://github.com/IQSS/dataverse-pm/issues/116

**Comment by cmbz** [comment]
## March 2024
- @sbarbosadataverse, @jggautier, and @cmbz met to discuss the status of https://github.com/IQSS/dataverse.harvard.edu/issues/230 and [Metadata recommendations from GREI Metadata and Search Subcommittee and Dataverse roadmap](https://docs.google.com/document/d/1qZLtkLT8P6vA5xYKFg-u1tpU6SCBlINfG1aNhd8rSdc/edit?usp=sharing), and identify and remove blockers.

**Comment by cmbz** [comment]
## Status: April 2024
- TBD

**Comment by jggautier** [comment]
## Status: May 2024

**Comment by cmbz** [comment]
## Status: June 2024
- Pending

**Comment by jggautier** [comment]
## Status: July 2024
-

**Comment by cmbz** [comment]
## Status: December 2024
- Metadata Coordination team decided on a course of action to move the implementation of GREI Metadata Recommendations forward:
  - https://github.com/IQSS/dataverse.harvard.edu/issues/326
  -  https://github.com/IQSS/dataverse/issues/11075
  -  https://github.com/IQSS/dataverse-pm/issues/356
  -  https://github.com/IQSS/dataverse-pm/issues/357

**Comment by cmbz** [comment]
## Status: January 2025
- ROR was added as an `Author Identifier Type` 
  - https://github.com/IQSS/dataverse/pull/11118

**Comment by cmbz** [comment]
## Status: February 2025
- Pending

**Comment by cmbz** [comment]
## Status: March 2025
- Pending

**Comment by cmbz** [comment]
# Status: May 2025
- External vocabulary scripts were deployed to Harvard Dataverse: https://github.com/IQSS/dataverse.harvard.edu/issues/326 was deployed
- The HDV implementation of the GREI Metadata Recommendations, V1 is now complete

**Comment by jggautier** [comment]
## Status: June 2025
- The NIH GREI metadata TG continues to work on v2 of the recommendations. See https://github.com/IQSS/dataverse-pm/issues/400#issuecomment-2997044207

**Comment by sbarbosadataverse** [comment]
## Status: October 2025
- https://github.com/IQSS/dataverse-pm/issues/439#issuecomment-3373164160

**Comment by sbarbosadataverse** [comment]
## Status: November 2025
- https://github.com/IQSS/dataverse.harvard.edu/issues/409#issuecomment-3548779337

**Comment by jggautier** [comment]
## Status: December 2025
- https://github.com/IQSS/dataverse.harvard.edu/issues/409#issuecomment-3648064363

**Comment by jggautier** [comment]
## Status: January 2026
- https://github.com/IQSS/dataverse.harvard.edu/issues/409#issuecomment-3813964634

**Comment by jggautier** [comment]
## Status: February 2026
- https://github.com/IQSS/dataverse.harvard.edu/issues/409#issuecomment-3915294905

**Comment by cmbz** [comment]
## Status: March 2026
- This issue has been reparented to fall under https://github.com/IQSS/dataverse-pm/issues/513, instead of Year 4. Work will be completed in Year 5

**Comment by jggautier** [comment]
## Status: April 2026
- In [the latest comment in the GitHub issue](https://github.com/IQSS/dataverse-pm/issues/470#issuecomment-4282171236), @jggautier reviewed the NIH GREI Metadata recommendations related to helping people find data based on when the data was published and when its files are available for download, summarized how we've designed Dataverse to include that information in the DataCite/Datacite exports it creates, and recommended next steps:
  - @jggautier followed up with folks from DataCite and from the NIH GREI group to make sure we understand their publication date recommendations
  - @jggautier opened two issues to describe what we should do to better align with these recommendations ([#12360](https://github.com/IQSS/dataverse/issues/12360) and [#12361](https://github.com/IQSS/dataverse/issues/12361)); added those two GitHub issues to the list of changes we're making to the DataCite/Datacite and OpenAIRE/oai_datacite exports ([#12281](https://github.com/IQSS/dataverse/issues/12281)); and closed the issue ([#470](https://github.com/IQSS/dataverse-pm/issues/470)) since the review is done and implementation is now being tracked in [#12281](https://github.com/IQSS/dataverse/issues/12281)
  - @jggautier suggested that we deprioritize any work related to the recommendations about helping people find data based on when the files can be downloaded, and that we tackle this later as part of a more dedicated effort.

**Comment by sbarbosadataverse** [comment]
## Status: July 2026

**Comment by sbarbosadataverse** [comment]
## Status: August 2026

**Comment by jggautier** [comment]
## Status: August 2026
- https://github.com/IQSS/dataverse/issues/12281#issuecomment-5700933153
