### ISSUE TITLE
Epic: NIH CAFE Grant Tasks

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#157]
## Overview
- This is an epic that pulls together all NIH CAFE grant tasks

## Tasks
- [x]  Finalize work here: https://github.com/IQSS/dataverse-pm/issues/22
- [x] Identify remaining NetCDF-related issues (e.g., geospatial support)
- [x] Establish if issues are of interest to members of the NIH CAFE team. If so:
  - [x] Queue for prioritization
  - [x] Address using NIH CAFE programmer once hired
- [x] Identify any additional issues

## Geospatial Issues
- [x] https://github.com/IQSS/dataverse/issues/9553
- [x] https://github.com/IQSS/dataverse/issues/9551
- [x] https://github.com/IQSS/dataverse/issues/9410
- [x] https://github.com/IQSS/dataverse/issues/5645
- [x] https://github.com/IQSS/dataverse/issues/6713
## Other Issues
- https://github.com/IQSS/dataverse/pull/9959
- https://github.com/IQSS/dataverse/issues/10194

**Comment by cmbz** [comment]
**2024/03/20**
- Closing in favor of new main project tracking issue: https://github.com/IQSS/dataverse-pm/issues/161
- Moving remaining issue: https://github.com/IQSS/dataverse/issues/10194 to the new tracking issue, linked above
