### ISSUE TITLE
Project: Croissant

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#163]
## Overview
- "Croissant is a high-level format for machine learning datasets that brings together four rich layers." 
- This issue tracks activities related to our collaboration with the Kaggle Team related to Croissant.

### Mission
- Make datasets easier to find and work with for Machine Learning, at scale and by diverse stakeholders (e.g. AI engineers, AI ethicists[e], compliance managers, interested public)

### Vision
- Croissant is the most convenient and widely used machine-readable format for ML-ready datasets.

### Issues we will probably work on

- [x] https://github.com/IQSS/dataverse/issues/10341
- [x] Announce that Croissant is ready for production use. [DONE](https://groups.google.com/g/dataverse-community/c/JI8HPgGarr8/m/T_ore2pmAgAJ).
- [x] https://github.com/IQSS/dataverse.harvard.edu/issues/294
- [x] https://github.com/IQSS/dataverse.harvard.edu/issues/294
- [x] https://github.com/IQSS/dataverse/issues/10542
- [ ] https://github.com/IQSS/dataverse-frontend/issues/350
- [ ] https://github.com/mlcommons/croissant/issues/530
- [x] Reindex datasets in Harvard Dataverse so that the "License" search facet is meaningful. Should be done as part of upgrading to 6.3:
  - https://github.com/IQSS/dataverse.harvard.edu/issues/285
- [ ] Include a facet for the Search API for datasets that only have files that are truly open (no custom terms, no guestbooks).
- [ ] Let Kaggle know how many dataset and bytes to expect when copying CC0 dataset from Harvard Dataverse (see [notes](https://docs.google.com/document/d/1xfrxjx-DpUBk-0uyXq_MlHDODdJEmarW0oO6U0nOF6k/edit?usp=sharing) from 2024-07-18 meeting and [Slack](https://iqss.slack.com/archives/C03R1E7T4KA/p1721397050046749))
- [ ] Let Kaggle know the best way to see when datasets have changed
- [ ] Commit data from Dataverse to Kaggle via CroissantML [via a button](https://iqss.slack.com/archives/C03R1E7T4KA/p1721397332904659?thread_ts=1721397050.046749&cid=C03R1E7T4KA), as an explicit action from the user. Is this part of a larger story around pushing data to other systems, such as data lakes?

### Issues we've opened or are keeping an eye on

Depending on the outcome of these issues, we may enhance our Croissant implementation to cover additional use cases.
- https://github.com/IQSS/dataverse/issues/11254
- https://github.com/mlcommons/croissant/issues/609
- https://github.com/mlcommons/croissant/issues/638
- https://github.com/mlcommons/croissant/issues/639
- https://github.com/mlcommons/croissant/issues/640
- https://github.com/mlcommons/croissant/issues/641
- https://github.com/mlcommons/croissant/issues/643
- https://github.com/mlcommons/croissant/issues/646
- https://github.com/mlcommons/croissant/issues/647
- https://github.com/mlcommons/croissant/issues/725

## Related
- [Google Drive Folder](https://drive.google.com/drive/folders/1xAg2_Ot8gc6S3_sspy7xt-wmgWsY8haZ?usp=drive_link)
- [Croissant GitHub Repo](https://github.com/mlcommons/croissant)
- https://github.com/IQSS/dataverse-pm/issues/155

**Comment by cmbz** [comment]
## Status: August 2024
- Croissant exporter added to both Harvard Dataverse and Demo (see https://github.com/IQSS/dataverse.harvard.edu/issues/294)

**Comment by cmbz** [comment]
## Status: September 2024
- Pending

**Comment by cmbz** [comment]
## Status: October 2024
- Pending

**Comment by cmbz** [comment]
# Status: November 2024
- Pending

**Comment by cmbz** [comment]
## Status: December 2024
- Pending

**Comment by pdurbin** [comment]
## DRAFT Status: January 2025

- https://github.com/IQSS/dataverse/pull/11045#issuecomment-2588067927
- https://github.com/mlcommons/croissant/pull/801

**Comment by pdurbin** [comment]
## DRAFT Status: February 2025

- merged: https://github.com/IQSS/dataverse/pull/11045

**Comment by pdurbin** [comment]
## DRAFT Status: March 2025

- spoke with @mrisdal about the NeurIPS Datasets & Benchmarks track potentially using Harvard Dataverse for dataset submissions but they need a Croissant file BEFORE the dataset is published so she created this feature request for us:
  - https://github.com/IQSS/dataverse/issues/11305
- [investigated](https://dataverse.zulipchat.com/#narrow/channel/379673-dev/topic/Croissant/near/503327799) the use of pyDataverse for creating a Croissant file before a dataset is published but I'm 95% it won't work as it also relies on export formats that are only available after the dataset is published.
  - I did create this PR to capture my attempts, at least: https://github.com/gdcc/dataverse-recipes/pull/6

**Comment by pdurbin** [comment]
DRAFT Status: May 2025

- merged: https://github.com/IQSS/dataverse/pull/11398 and https://github.com/gdcc/exporter-croissant/pull/14
- Wrote a script to download Croissant files from a draft dataset: https://github.com/gdcc/dataverse-recipes/pull/19

**Comment by cmbz** [comment]
## Status: August 2025
- Pending

**Comment by pdurbin** [comment]
## Status: October 2025
- Fixed Maven Central config to allow publishing of the Croissant exporter
- Published Croissant 0.1.6 with the following fix:
  - https://github.com/gdcc/exporter-croissant/pull/20
- Proposed addition to Dataverse 6.9 release notes about the fix:
  - https://github.com/IQSS/dataverse/pull/11902
- Discussing with Croissant spec authors about the use of `@id` for file paths. https://github.com/mlcommons/croissant/issues/639 has been re-opened after a bug regarding whitespace in filenames was opened at https://github.com/gdcc/exporter-croissant/issues/22
- Created a new issue after discussing with @cmbz:
  - https://github.com/gdcc/exporter-croissant/issues/24

**Comment by rnichols7** [comment]
## Status: November 2025
- Prep for a Croissant 1.1 release:
  - https://github.com/gdcc/exporter-croissant/pull/31

**Comment by pdurbin** [comment]
## Status: December 2025
- Prep for a Croissant 1.1 release:
  - https://github.com/gdcc/exporter-croissant/pull/33
  - https://github.com/gdcc/exporter-croissant/pull/35
- Attended two Croissant working group meetings

**Comment by pdurbin** [comment]
## Status: January 2026
- Prep for a Croissant 1.1 release:
  - Start investigating the following:
    - It looks like on Jan 6 https://github.com/mlcommons/croissant/pull/990 was merged which adds a section to the Croissant spec about supporting descriptive statistics. Here's a preview (draft 1.1 spec): https://docs.mlcommons.org/croissant/docs/croissant-spec-1.1.html#application-representing-descriptive-statistics
- Made a PR to move Croissant into the main codebase
  - https://github.com/IQSS/dataverse/pull/12130
- Created issues for after the PR above is merged
  - https://github.com/IQSS/dataverse/issues/12123
  - https://github.com/IQSS/dataverse/issues/12014
  - https://github.com/IQSS/dataverse/issues/12124
- Created a view to track Croissant work
  - https://github.com/orgs/IQSS/projects/34/views/50

**Comment by rnichols7** [comment]
## Status: February 2026

- Waiting for the pull request https://github.com/IQSS/dataverse/pull/12130 that I made to be merged.
- Made the pull request https://github.com/IQSS/dataverse/pull/12191
  - Also, communicated to Croissant spec leads and Slava and Pascal about this PR.
- Created  https://github.com/IQSS/dataverse/issues/12150 that can be worked on independently of the Dataverse code and helped @cmbz come up with a first draft.
- Attended Croissant Task Force meetings, especially to learn about about Croissant 1.1 and when it will ship.

**Comment by pdurbin** [comment]
## Status: March 2026

- Made pull request https://github.com/IQSS/dataverse/pull/12214
