### ISSUE TITLE
GREI 5: HDV Task - Indigenous Data Support

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#170]
## Overview
- TK Label Working Group developed an NIH GREI grant proposal to support indigenous data sovereignty. See: [IDS SUPPORT AND NIH-GREI GRANT](https://docs.google.com/document/d/1z3TGBFvz6MboYaLIEtOfyR5cZGWgQhjQy6DuuUq8q-s/edit?usp=sharing)
- TKLWG is developing a proposed integration with Dataverse with the following goals:
  - Link to and incorporate identified sources for indigenous knowledge representation, such as TKLabels and Notices
  - Curation processes for managing the creation, reading, updating and deleting of metadata (including an data access workflow); and
  -  Present curated metadata (e.g. TKLabels and TKNotices) in catalog records
  - Allow external aggregators to harvest this metadata (specifically the IDN Data Catalog, but preferably standardized model that allows for multiple external parties to harvest).
  - [Documentation in process: The updated docs in progress for Dataverse are at](: https://dataverse-guide--11904.org.readthedocs.build/en/11904/installation/localcontexts.html) 

## DataCite and Metadata related discussions
[Meeting Notes](https://docs.google.com/document/d/1SGMcFE7EZbLfFbDyMC7fVMEoYlURTm2r51vSOuExnPk/edit?tab=t.0
)

## Tasks

- [x] Confirm that the goals described in [IDS SUPPORT AND NIH-GREI GRANT](https://docs.google.com/document/d/1z3TGBFvz6MboYaLIEtOfyR5cZGWgQhjQy6DuuUq8q-s/edit?usp=sharing) are the final goals for the use case.
- [x] Update proposed integration based upon Working Group and user feedback
- [x] Coordinate with Ramin Soleymani-Fard, member of the LICCI team at ICTA-UAB, to evaluate his current work to develop a Dataverse metadata block for Local Context metadata
- [x] Install on demo
- [x] #316
- [x] Decide best UX approach (preferred, Dataverse looks for LC projects with dataset DOI)
- [x] Design approach
- [x] Implement approach
- [x] Retest - invite community on Zulip and Google Community to [test](https://demo.dataverse.org/dataverse/LCtests) and provide feedback in [Issue](ttps://github.com/IQSS/dataverse-pm/issues/316)
- [x] Changes on Local Contexts now requires changes to the technical plan (as of 2/27/25/)
- [x] Add functionality to Beta to be tested until 6.7 release is ready.
- [x] DV software Become an integration partner (SB) - cost waived for two years once activated
- [x] #322
- [x] #471
- [ ] Convene repository managers working group to discuss announcing and workflow management of feature (HDV, QDR, BRAZIL, ANU, OSF)
- [ ] Work with Datacite, Ted Haberman, LC, Jim to establish metadata export
- [ ] Pilot project:  recruite projects to test the integration, help cleanup documentation, do a webinar as final step
- [ ] Add to Guide: New Feature, How to Use, and Tooltips on production
- [ ] Install on HDV and promote
- [x] Create the software level documentation
- [ ] Create the institutional-level documentation (and use cases), mockup to demonstrate workflow to Institutions, Researchers
- [ ] Is Harvesting (from other DV installations) a possibility? As long as the project is public, and Harvard is connected in the LC Hub
- [ ] Ongoing management and access to this service at the user level
- [ ] Create working group charter on GDCC
- [ ] Boilerplate language on adding to DMSP any plans to use labels and notices in their project
- [ ] LC/DV Advisory Board is composed of the LC technical board, DV community members, and Indigenous Community Leaders (Metadata bundle group Indigenousdatalab.org)

## Related
- https://github.com/IQSS/dataverse/pull/12224
- https://github.com/IQSS/dataverse.harvard.edu/issues/297
- https://github.com/IQSS/dataverse-pm/issues/370
- https://github.com/IQSS/dataverse-pm/issues/124
- [From 6.9 Release Notes](https://github.com/IQSS/dataverse/releases) Integration with Local Contexts has been updated to support the change in their API regarding how DOIs entered as "Optional Project Information" are represented. See [the guides](https://guides.dataverse.org/en/6.9/installation/localcontexts.html) and https://github.com/IQSS/dataverse/pull/11904.

## Resources
- [Main Notes Document for LC/DV Integration](https://docs.google.com/document/d/1xXLN4e0Xh2q_OUJgfB28CkmPzIQh91TTWc8olEz26pQ/edit?usp=sharing)
- [DV/LC and DataCite Meeting Notes](https://docs.google.com/document/d/1SGMcFE7EZbLfFbDyMC7fVMEoYlURTm2r51vSOuExnPk/edit?tab=t.0#heading=h.fih9akfp3i6x)
- [Dataverse Integration Partner Guide Addendum](https://docs.google.com/document/d/14KRdQe1nie4p0oC2pgxd4z_70LJK7cS5b_HYw-m4rn4/edit?tab=t.ugdtjodn2wgs)
- [Dataverse Guide/GitHub README file](https://github.com/gdcc/dataverse-external-vocab-support/blob/lc2/packages/local_contexts/README.md)
- [TKLabels: Design Options for Integrating with Dataverse](https://docs.google.com/document/d/1umSncPhXApNcvstzqMbqIfx87LCB3RqwS69gPCvbDVE/edit?usp=sharing) (Document)
- [DRAFT Policy, workflows for Installation Level](https://docs.google.com/presentation/d/1xNSDY4kdzX5kril1lCujg_1FsHTGz8DpjXOeOVsPJYc/edit?slide=id.g39a2414f5b8_0_23#slide=id.g39a2414f5b8_0_23)
- Local Contexts repository: https://github.com/localcontexts/localcontexts-metadata
- [DRAFT: Year 3 Realignment Proposal Plan](https://docs.google.com/document/d/1ADskSIH6T4LGt8Lz4eibzNOq4lnzGNxu/edit?usp=drive_link&ouid=102516728224230315414&rtpof=true&sd=true) (Document)
- [NIH GREI Aim 2 Yearly Progress (Year 2)](https://docs.google.com/document/d/1kwkXucTlbEMl82dCoAu-l80MVRKzdFQb5g88B2g5K4U/edit?usp=sharing) (Document)
- [Integration proposal by JM](https://docs.google.com/document/d/1umSncPhXApNcvstzqMbqIfx87LCB3RqwS69gPCvbDVE/edit?pli=1#heading=h.w5gbovoa191i)
- Initiated plans to join the [TK Labels Service Provider Early Adopter Program](https://localcontexts.org/service-provider-early-adopter-program/)
- [Indigenous Metadata Bundle COMMUN I QUÉ INDIGENOUS METADATA SYMPOSIUM](https://drive.google.com/drive/folders/1kVZCDDVmApHAuqNq_3TZC8dJkIv92BBS)

- [LC/DV Policy_Working Group Roster](https://docs.google.com/spreadsheets/d/1ULzZjqfrHnmVCIATZJad8yH3OPGeCK2pyAHUJfq4EfQ/edit?gid=0#gid=0)

**Comment by cmbz** [comment]
## Status: April 2024
- Pending

**Comment by sbarbosadataverse** [comment]
## Status: May 2024
- Jim provided responses to the questions on the integration proposal (see resources above) provided by Ramin and Janet
- Initiated plans to join the [TK Labels Service Provider Early Adopter Program](https://localcontexts.org/service-provider-early-adopter-program/) - meeting scheduled for June (SB will try to join and invited Laura (Brazil) and Amber (Borealis) to join the meeting

**Comment by cmbz** [comment]
## Status: July 2024
- Pending

**Comment by cmbz** [comment]
## Status: August 2024
- Local Context controlled vocabulary support implemented on demo.dataverse.org
  - https://github.com/IQSS/dataverse.harvard.edu/issues/297

**Comment by sbarbosadataverse** [comment]
Shared with TKLabel interest group and Brazilian Installation that has been waiting on this feature.

**Comment by amberleahey** [comment]
Thanks for adding this into the demo repository. I tested the LC metadata block and field for a dataset and noticed that when I search for term "name" I was able to make a linkage to a record in the LC Hub. May want to think about how to instruct people to use this, perhaps encourage them to visit the LC Hub for more information about registering projects for linkage before adding to Dataverse metadata? After adding, I wasn't able to delete the linkage it just appeared as greyed out once added. After saving, this did appear to retrieve the TK Labels image and name for display in DV Metadata. I couldn't figure out how to enable this field for display in the Terms or the main dataset landing page citation area for appearing alongside other dataset terms such as licenses. 
<img width="1201" alt="Screen Shot 2024-08-30 at 3 50 48 PM" src="https://github.com/user-attachments/assets/a747d1c1-4310-4e56-b122-39adfd902522">
<img width="1126" alt="Screen Shot 2024-08-30 at 4 02 07 PM" src="https://github.com/user-attachments/assets/0754e925-e0f3-411c-813d-207138e93f75">

**Comment by qqmyers** [comment]
FYI: While there were more issues than I expected, I've been able to update the Local Contexts script to address the problem of not being able to delete a project, and have made it configurable so test instances can point to the Local Contexts sandbox rather than their production site.  I also managed to find a work-around to enable the Local Contexts information to appear on the main dataset page without having to wait for a change in Dataverse core (rather than just far down on the metadata pane).

I've updated https://docs.google.com/document/d/1umSncPhXApNcvstzqMbqIfx87LCB3RqwS69gPCvbDVE/edit?usp=sharing to include instructions on how to deploy the LC capability and to include more information about what has been fixed/improved in the script.

I'll push these changes to github next week and coordinate with @stevenwinship to deploy them to https://demo.dataverse.org .

**Comment by qqmyers** [comment]
Demo has been updated by doing the following:

- Updating the LocalContexts External Vocabulary configuration:
`curl -X PUT --upload-file combined-cvoc-conf.9.3.24.json http://localhost:8080/api/admin/settings/:CVocConf`
(combined-cvoc-conf.9.3.24.json has the same set of fields as the previous setting (from combined-cvoc-conf.json) with the changes for LocalContexts from the https://github.com/gdcc/dataverse-external-vocab-support repo.)
 
- Adding display of LocalContexts info above-the-fold on the dataset page:
`curl -X PUT -d "dsDescription,subject,keyword,publication,notesText,LCProjectUrl" http://localhost:8080/api/admin/settings/:CustomDatasetSummaryFields
` 

- Addition of a published https://demo.dataverse.org/dataverse/LCtests collection for testing. 
 

**Note:** I suggest that someone with the ability to admin the root collection turn off the LocalContexts metadatablock at that level (mirroring how we expect this to be used - with LocalContexts only used on some child collections).

![image](https://github.com/user-attachments/assets/1f2f02df-7adf-448e-aaf3-e83e075c3509)

**Comment by qqmyers** [comment]
In the call today: Ashley showed us how DOI lookup almost works with their current code and she is going to make some updates in a week or so to allow it to work (two issues: they allow DOIs in multiple fields, but right now only the provider_id field is indexed, and, while they allow free form text, so we could get https://doi.org/10.5072/ABCDEF or doi:10:5072/ABCDEF etc, a search for 10.5072/ABCDEF doesn't work right now because they aren't breaking the strings up when indexing.) It sounds like searching per field will be allowed in v2, and there will be changes in the returned JSON, so we should expect some details to change. We also discussed how a link might be reported to DataCite or in the schema.org export, etc. and Ashley said she'd get us info on the draft recommendation for the DataCite mapping. It sounds like the schema.org mapping discussion is not as far along.

- I said I would go ahead with the current script to add some accessibility improvements I just made for the ROR and ORCID scripts.
- Ramin is going to create a PR to add a config change that will make it possible to add an LC Project id via the API.
- When Ashley's changes are made, we can look at updating how input is done along [the lines discussed in the design doc](https://docs.google.com/document/d/1umSncPhXApNcvstzqMbqIfx87LCB3RqwS69gPCvbDVE/edit#heading=h.19rf6vvial9z).
- If getting a DataCite mapping in is a priority (i.e. if we want it in v6.4), we'll need to move very quickly as v6.4 is starting to get frozen (no new work).

**Comment by sbarbosadataverse** [comment]
-The tasks were updated to include a broader retest by the DV community and documentation work for the Guide. An invite to test and input feedback will be added to Zulip and DV Google Group, with a deadline.

**Comment by cmbz** [comment]
## Status: December 2024
- Pending

**Comment by sbarbosadataverse** [comment]
## Status: January 2024

We have feedback on the [issue](https://github.com/IQSS/dataverse-pm/issues/316#issuecomment-2570942006) to have the metadata of a LC projected as part of the dv metadata.

**Comment by cmbz** [comment]
## Status: February 2024
- Pending

**Comment by sbarbosadataverse** [comment]
## Status: March 2024

- Changes between Local Context and the feature on DV has been resolved but not in time to release in 6.6
- Add to Beta to allow demo/testing before 6.7 release (scheduled for June)

**Comment by cmbz** [comment]
## Status: April 2025
- Pending

**Comment by cmbz** [comment]
## Status: June 2025
- Pending

**Comment by sbarbosadataverse** [comment]
## Status: August 2025
- Pending (release 6.7)
- Institution Account created, waiting on invoice (1200/yearly)
- Integration membership cost waived for (when activated) 2 years -

**Comment by cmbz** [comment]
## Status: September 2025
- Pending

**Comment by sbarbosadataverse** [comment]
## Status: November 2025
- HDV institutional membership is active:

L.E. Brown
Thu, Nov 13, 12:19 PM (4 days ago)
to me, Local, Ashley, Local

Dear Sonia,

We are writing to confirm that we have processed the completed agreement and confirmed payment for The Harvard Dataverse Repository's small institutional subscription with Local Contexts.

[The Harvard Dataverse Repository](https://localcontextshub.org/institutions/view/209/) account is now active in the [Local Contexts Hub](https://localcontextshub.org/), and you have full access to your subscription counts: 3 administrators, 1 API key, 15 Projects, and 24 Notices.

Thank you again for your support, and we look forward to supporting your usage of Local Contexts. Please don't hesitate to reach out with any questions!


Kind regards,
L.E.
Local Contexts Logo

L.E. Brown (she/her)

Subscriptions Coordinator

Website: [localcontexts.org](https://localcontexts.org/)

Email: [support@localcontexts.org](mailto:support@localcontexts.org)

TimeZone: [PT](https://www.timeanddate.com/worldclock/usa/los-angeles)

**Comment by sbarbosadataverse** [comment]
## Status: December 2025

- Amber drafted a policy/workflows document for the working group
- Doodle poll to convene working group meeting on policy and workflows sent (including Erin from Metadata gamechangers)
- [Ist meeting of DataCite and LC group to discuss action items](https://docs.google.com/document/d/1SGMcFE7EZbLfFbDyMC7fVMEoYlURTm2r51vSOuExnPk/edit?tab=t.0) 

- Added to tasks:

  1 - Metadata /DataCite issues
  2 - Boilerplate language for  DMSP use
  3 - Follow-up with Kelly (DataCite) on metadata action item questions
  4 - Advance search improvements to capture LC metadata
  5 - Open to collaboration notice maybe can be configured to open all related datasets?
  6 - Additional Facet options to make LC data discoverable?
  7 - LC has a taxonomy that we may be able to adopt into support documents.

**Comment by sbarbosadataverse** [comment]
## Status: January 2026
- The LC/DV [Policy working group](https://docs.google.com/presentation/d/1xNSDY4kdzX5kril1lCujg_1FsHTGz8DpjXOeOVsPJYc/edit?slide=id.g3b9be3ac5a5_0_5#slide=id.g3b9be3ac5a5_0_5) had it's 1st meeting, where Amber presented on the Installation level set up of the integration, and we started discussing policy questions

- A proposal abstract was submitted to 2026DCM

**Comment by sbarbosadataverse** [comment]
## Status: February 2026
- Waiting to hear: proposal abstract was submitted to 2026DCM
- Working on draft policies/workflows for HDV

**Comment by sbarbosadataverse** [comment]
## Status: March 2026
### end year 4

**Comment by cmbz** [comment]
2026-03-13: This use case task will continue in GREI Y5.

**Comment by sbarbosadataverse** [comment]
Working on 2026DCM slides: https://docs.google.com/presentation/d/1_e44ZrBKpB61dYxYTzA8Wd0qZvsUG-zhEDGR15OPf2M/edit?slide=id.g397a5d8441b_0_279#slide=id.g397a5d8441b_0_279

**Comment by cmbz** [comment]
## Status: August 2026
- Pending
