### ISSUE TITLE
GREI 3: HDV Task - Improve OAI-PMH Harvesting

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#171]
## Overview
"Our proposed project will significantly improve the widely-used Harvard Dataverse repository to better support NIH-funded research. A critical measure of the GREI program’s success is to standardize the discoverability across generalist repositories. 

To help with this, we propose to improve the existing harvesting functionality in the Dataverse software based on the Open Archives Initiative Protocol for Metadata Harvesting (OAI-PMH) standard, and coordinate with other repository packaging standards to share or move metadata and data. Dataverse already supports the Bags as defined by the Research Data Alliance (RDA) Research Data Repository Interoperability Working Group. 

Here we proposed to improve the support for Bags, test it for NIH-funded datasets, and explore and define the appropriate standard to use to move the metadata and data across generalist repositories This will help with a sustainable and succession plan - if one repository cannot support anymore a specific dataset, it will allow to easily move the dataset to another repository without losing any information about the dataset." ([Source](https://docs.google.com/document/d/1cFK8pdwMKIRZxNs8EZXL1cXmW0ho6Rx9ulCewJ1ZCFI/edit?usp=sharing))

### New Features
Support harvesting from DataCite's OAI-PMH API
- [x] #330
- [x] https://github.com/IQSS/dataverse/issues/10909

### Spikes
- [x] https://github.com/IQSS/dataverse-pm/issues/25
- [x] https://github.com/IQSS/dataverse-pm/issues/85
- [x] https://github.com/IQSS/dataverse.harvard.edu/issues/92
  - https://help.hmdc.harvard.edu/Ticket/Display.html?id=322153 (Borealis)
  - https://help.hmdc.harvard.edu/Ticket/Display.html?id=329544 (DataverseNO)
  - https://help.hmdc.harvard.edu/Ticket/Display.html?id=330637 (Roper Center)
- [ ] https://github.com/IQSS/dataverse-pm/issues/100

#### In Progress
- [ ] https://github.com/IQSS/dataverse.harvard.edu/issues/243 - essentially done (we have harvested their metadata and their datasets are searchable by our users). we are keeping the issue open because we asked the devs at SRDA to improve something on their end, so this is for us to remember to check on the progress.
- [x] https://github.com/IQSS/dataverse.harvard.edu/issues/204 - this is pending on Roper devs. fixing something on their end. We have reestablished contact and communicated what the issues are. 
  - https://help.hmdc.harvard.edu/Ticket/Display.html?id=330637
- [ ] https://github.com/IQSS/dataverse.harvard.edu/issues/408
  - [ ] https://github.com/IQSS/dataverse/issues/11933
  - [ ] https://github.com/IQSS/dataverse/issues/11932
- [x] https://github.com/IQSS/dataverse/pull/11217

#### Complete
- [x] https://github.com/IQSS/dataverse/issues/8632
- [x] https://github.com/IQSS/dataverse/issues/10936
- [x] https://github.com/IQSS/dataverse/issues/10937
- [x] https://github.com/IQSS/dataverse/issues/8129
- [x] https://github.com/IQSS/dataverse/issues/8578
- [x] https://github.com/IQSS/dataverse/issues/10611
- [x] https://github.com/IQSS/dataverse/issues/10734
- [x] https://github.com/IQSS/dataverse/issues/8243 - complete
- [x] https://github.com/IQSS/dataverse/issues/8629
- [x] https://github.com/IQSS/dataverse/issues/3322
- [x] https://github.com/IQSS/dataverse/issues/8005
- [x] https://github.com/IQSS/dataverse.harvard.edu/issues/153
- [x] https://github.com/IQSS/dataverse/issues/7624 
- [x] https://github.com/IQSS/dataverse.harvard.edu/issues/142
- [x] https://github.com/IQSS/dataverse/issues/3437
- [x] https://github.com/IQSS/dataverse/pull/10222
- [x] https://github.com/IQSS/dataverse/issues/9992
- [x] https://github.com/IQSS/dataverse/issues/10329
- [x] https://github.com/IQSS/dataverse.harvard.edu/issues/251
- [x] https://github.com/IQSS/dataverse/pull/10323 - _almost_ done (currently in QA)
- [x] https://github.com/IQSS/dataverse/issues/10254 - for the most part, the fix already exists (added to the prod. 6.1 patch - that's what made it possible to harvest from SRDA, next item on the list)
- [x] https://github.com/IQSS/dataverse/issues/8578
- [x] https://github.com/IQSS/dataverse/issues/8129
- [x] https://github.com/IQSS/dataverse/issues/5392
- [x] https://github.com/IQSS/dataverse/issues/3699
- [x] https://github.com/IQSS/dataverse/issues/8512
- [x] https://github.com/IQSS/dataverse/issues/3276
- [x] https://github.com/IQSS/dataverse/issues/3298
- [x] https://github.com/IQSS/dataverse/issues/7074
- [x] https://github.com/IQSS/dataverse/issues/4831
- [x] https://github.com/IQSS/dataverse/issues/3290
- [x] https://github.com/IQSS/dataverse/issues/7052
- [x] https://github.com/IQSS/dataverse/issues/3316
- [x] https://github.com/IQSS/dataverse/issues/3314
- [x] https://github.com/IQSS/dataverse/issues/3315
- [x] https://github.com/IQSS/dataverse/issues/7108
- [x] https://github.com/IQSS/dataverse/issues/7127
- [x] https://github.com/IQSS/dataverse/issues/4859
- [x] https://github.com/IQSS/dataverse/issues/2721
- [x] https://github.com/IQSS/dataverse/issues/5960
- [x] https://github.com/IQSS/dataverse/issues/9294
- [x] https://github.com/IQSS/dataverse/issues/8703

#### Pending
These issues will be sized and prioritized once the _In Progress_ issues are closed.
- [ ] https://github.com/IQSS/dataverse/issues/7727
- [ ] https://github.com/IQSS/dataverse/issues/8842
- [ ] https://github.com/IQSS/dataverse/issues/7243
- [ ] https://github.com/IQSS/dataverse/issues/8630
- [ ] https://github.com/IQSS/dataverse/issues/8631
- [ ] https://github.com/IQSS/dataverse.harvard.edu/issues/63

### Additional Harvesting Issues (Year 4)
These issues will be prioritized during GREI Year 4 Planning.

- https://github.com/IQSS/dataverse/issues/5920
- https://github.com/IQSS/dataverse/issues/11916
- https://github.com/IQSS/dataverse/issues/4176
- https://github.com/IQSS/dataverse/issues/4025
- https://github.com/IQSS/dataverse/issues/7330
- https://github.com/IQSS/dataverse/issues/9344
- https://github.com/IQSS/dataverse/issues/9438
- https://github.com/IQSS/dataverse/issues/9079
- https://github.com/IQSS/dataverse/issues/8778
- https://github.com/IQSS/dataverse/issues/9318
- https://github.com/IQSS/dataverse/issues/7546
- https://github.com/IQSS/dataverse/issues/8815
- https://github.com/IQSS/dataverse/issues/10195
- https://github.com/IQSS/dataverse/issues/10042
- https://github.com/IQSS/dataverse/issues/9686
- https://github.com/IQSS/dataverse/issues/8306
- https://github.com/IQSS/dataverse/issues/9261
- https://github.com/IQSS/dataverse/issues/8739
- https://github.com/IQSS/dataverse/issues/7453
- https://github.com/IQSS/dataverse/issues/1592
- https://github.com/IQSS/dataverse/issues/8693
- https://github.com/IQSS/dataverse.harvard.edu/issues/72
- https://github.com/IQSS/dataverse/issues/10396
- https://github.com/IQSS/dataverse/issues/8630
- https://github.com/IQSS/dataverse/issues/8631

## Related
- https://github.com/IQSS/dataverse/issues/10469 (Solr indexing maybe affecting performance)

## Resources
- https://github.com/IQSS/dataverse-pm/issues/124
- https://github.com/IQSS/dataverse-pm/issues/117
- List of repositories to harvest: [here](https://docs.google.com/document/d/1i-cpu7-ul48m2r1hTw9zs_-yE5JN9rrzkG2VHtJO0m4/edit#bookmark=id.bl5b50ih6o6y)
- [NIH OTA](https://docs.google.com/document/d/1cFK8pdwMKIRZxNs8EZXL1cXmW0ho6Rx9ulCewJ1ZCFI/edit?usp=sharing)
- [Google Drive Folder](https://drive.google.com/drive/u/0/folders/0ACthvafpCn06Uk9PVA)
- [Monthly Status Reports](https://drive.google.com/drive/folders/11nQBFXKL3jGq8E2HLkcTWmcSu3xCupS8?usp=drive_link)
- [APPROVED - NIH GREI Coopetition Plan Year 3](https://docs.google.com/document/d/1XTJSOfUlg06WYGXe3URVFH6VaPMkBNPqVZgrsqOrbc0/edit?usp=sharing)
- [DRAFT: Year 3 Realignment Proposal Plan](https://docs.google.com/document/d/1ADskSIH6T4LGt8Lz4eibzNOq4lnzGNxu/edit?usp=drive_link&ouid=102516728224230315414&rtpof=true&sd=true)
- [Spreadsheet with info about Dataverse repositories that Harvard Dataverse is harvesting metadata from](https://docs.google.com/spreadsheets/d/1ek3AMYDWBo3ck6D18Q47FL1lTDbkLbf7tWhHliVtjbQ)

**Comment by cmbz** [comment]
## January 2024 Report
#### Completed
- https://github.com/IQSS/dataverse.harvard.edu/issues/153 (2024/01/19)
- https://github.com/IQSS/dataverse/issues/7624 (2024/01/30)
- https://github.com/IQSS/dataverse.harvard.edu/issues/142 (2024/01/04)
- https://github.com/IQSS/dataverse/issues/8005 (2024/01/05)

**Comment by cmbz** [comment]
## February 2024
### Completed
- https://github.com/IQSS/dataverse/issues/3437

**Comment by cmbz** [comment]
## March 2024
- TBD

**Comment by cmbz** [comment]
## April 2024
- TBD

**Comment by cmbz** [comment]
## May 2024
- TBD

**Comment by cmbz** [comment]
@jggautier Great thanks! When you do, please update the June status comment, too https://github.com/IQSS/dataverse-pm/issues/171#issuecomment-2009648663

**Comment by cmbz** [comment]
## Status: July 2024
- Closed: https://github.com/IQSS/dataverse/issues/4859

**Comment by cmbz** [comment]
## Status: August 2024
- Pending

**Comment by cmbz** [comment]
## Status: September 2024
- Pending

**Comment by cmbz** [comment]
## Status: October 2024
-

**Comment by cmbz** [comment]
## Status: November 2024
The following harvesting-related PRs were merged: 
- https://github.com/IQSS/dataverse/pull/10990
- https://github.com/IQSS/dataverse/pull/10837
- https://github.com/IQSS/dataverse/pull/11003
- https://github.com/IQSS/dataverse/pull/10772
- https://github.com/IQSS/dataverse/pull/10996
- https://github.com/IQSS/dataverse/pull/10990

**Comment by cmbz** [comment]
## Status: January 2025
- Pending

**Comment by cmbz** [comment]
## Status: March 2025
- Work to harvest metadata from DataCite was completed: [Add support for OAI-harvesting from DataCite dataverse#10909](https://github.com/IQSS/dataverse/issues/10909)
- Installations can now customize their harvesting clients' names: https://github.com/IQSS/dataverse/pull/11217

**Comment by jggautier** [comment]
## Status: August 2025
- No updates

**Comment by sbarbosadataverse** [comment]
## Status: November 2025
- We restarted weekly harvesting of almost all repositories and described a couple of bugs that prevent Dataverse from harvesting certain dataset records ([#11932](https://github.com/IQSS/dataverse/issues/11932), [#11933](https://github.com/IQSS/dataverse/issues/11933))

**Comment by sbarbosadataverse** [comment]
## Status: December 2025
- No updates

**Comment by sbarbosadataverse** [comment]
## Status: January 2026
- No updates

**Comment by sbarbosadataverse** [comment]
## Status: February 2026
- Harvested all of ICPSR's records into Harvard Dataverse ([#63](https://github.com/IQSS/dataverse.harvard.edu/issues/63)) by using DataCite's OAI-PMH feed
- Added a setting for configuring a limit on outgoing calls in the Harvesting Client ([#11473](https://github.com/IQSS/dataverse/issues/11473)), to make it easier to harvest from large collections of records

**Comment by jggautier** [comment]
## Status: March 2026
- @jggautier, @scolapasta and @landreev  will review the existing open harvesting issues to decide which should be moved onto the Year 5 list.
