### ISSUE TITLE
Project: Pilot Large Data Support Service

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#178]
## Overview
Pilot Harvard Dataverse large data support services using NESE tape resources for several datasets from Harvard affiliates.

## Tasks
- [x] Identify prospective data collections
- [x] Confirm pilot participants
- [x] Coordinate with pilot collection owners to estimate collection size and curation needs
- [x] Create Harvard Dataverse collections
- [x] Coordinate with NESE support staff for tape provisioning
- [x] Coordinate with data collection owners, NESE support, and Dataverse team to upload data
- [x] Coordinate with IQSS finance re. costs
- [ ] Assess pilot and propose workflow improvements

### Process Development and Management
- [x] Develop an intake process including basic and extended consultation process
- [x] Develop and launch RT queue, including service attributes (will map to service offerings)
- [x] Develop large data collection intake form @sbarbosadataverse
- [ ] Define what is included in the Large Data Technical Support service component
- [x] Define what is included in the Large Data Administration service component
- [ ] Define what is included in the Large Data Monitoring service component
- [x] End-user instructions for NESE data access, add to Dataverse documentation in Guide and HDV support website
- [x] Document large data curation services process (see hdv-curation issues on large data)

## Team
- @sbarbosadataverse 
- @cmbz 
- @qqmyers 
- @landreev 

### School of Engineering and Applied Sciences (Harvard SEAS)
- https://github.com/IQSS/dataverse-HDV-Curation/issues/594

### Terabyte-Scale Dataset for Partial Discharge 2 Detection in Covered Conductors via Contact 3 Galvanic Method
-https://db.cs.vsb.cz/datacolls/pdp2020/
-https://help.hmdc.harvard.edu/Ticket/Display.html?id=366158&results=56072ee681951385a6015bad30361ae4

### The Oregon-Massachusetts Mammography Database (OMAMA-DB) 
See also: https://fly.cs.umb.edu/omama/ and https://github.com/IQSS/dataverse-HDV-Curation/issues/443
  - Size: 8T
  - Contact: Daniel Haehn, SEAS & UMass Boston

### GEOS-Chem 1 and 10 year Benchmark data
*recontact early next year - they lost staff and can't devote to this effort at this time
See also:  
 https://help.hmdc.harvard.edu/Ticket/Display.html?id=361614
https://github.com/IQSS/dataverse-HDV-Curation/issues/456
- Datasets
  - http://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/
  - http://ftp.as.harvard.edu/gcgrid/geos-chem/10yr_benchmark
  - Size: about 1.6 TB: 
    - 484G    10yr_benchmarks/
    - 484G    total
    - 1.1T      1yr_benchmarks/
    - 1.1T      total
  - Note: It would increase as they add new benchmark output. typically release model versions once per quarter.  Prior to each release they would generate 1 or more benchmark runs for GCClassic and GCHP.   The 10 year benchmarks are generated once per major version release which are less frequent.  

### DrivAerNet: A Parametric Car Dataset for Data-driven Aerodynamic Design and Graph-Based Drag Prediction
See also: https://github.com/IQSS/dataverse-HDV-Curation/issues/444

- [x] moving their ‘streamlined’ dataset (<1TB) to the [DeCoDE lab’s dataverse](https://dataverse.harvard.edu/dataverse/decode-mit)
- <1TBish
- File sizes: Largest: 1.6G and smallest: 400bytes,
- Total number of files: not sure, user quoted 10^6, but was fuzzy on that.
- File types: .tar.gz, txt, vtk, stl, .sh, data will be packed in .zip format
- [x] By mid to end of May: the full 16TB. 
- [ ] Author needs to repackage one dataset to meet packaging standards

## Under discussion for support
-https://help.hmdc.harvard.edu/Ticket/Display.html?id=362556
-https://help.hmdc.harvard.edu/Ticket/Display.html?id=358471

## Related RT Tickets
- [x] [#356558: Harvard Dataverse support request: Hosting of breast cancer database
](https://help.hmdc.harvard.edu/Ticket/Display.html?id=356558)
- [ ] https://help.hmdc.harvard.edu/Ticket/Display.html?id=361614 

## Issues
- [ ] https://github.com/IQSS/dataverse.harvard.edu/issues/305
- [x] https://github.com/IQSS/dataverse/pull/10451
- [x] https://github.com/IQSS/dataverse.harvard.edu/issues/261
- [x] https://github.com/IQSS/dataverse.harvard.edu/issues/260

## Related
- https://github.com/IQSS/dataverse-pm/issues/268
- https://github.com/IQSS/dataverse-pm/issues/176
- https://github.com/IQSS/dataverse-pm/issues/154
- https://github.com/IQSS/dataverse-pm/issues/105
- https://github.com/IQSS/dataverse.harvard.edu/issues/254
- https://github.com/IQSS/dataverse/issues/10623

## Resources
- [Google Drive Folder](https://drive.google.com/drive/folders/1w9sqBoCrThNJKNhT3JX683UscPqBovNT?usp=drive_link)

**Comment by cmbz** [comment]
## Status: March 2024
- Our pilot for computing on large data was completed. See follow up: https://github.com/IQSS/dataverse-pm/issues/184
### Closed
- https://github.com/IQSS/dataverse-pm/issues/105

**Comment by cmbz** [comment]
## Status: April 2024

**Comment by sbarbosadataverse** [comment]
## Status: April 2024

**Comment by sbarbosadataverse** [comment]
## Status: June 2024
OMAMA collection updated with NESE download instructions and checklist for curation completion: https://github.com/IQSS/dataverse-HDV-Curation/issues/443

**Comment by cmbz** [comment]
## Status: July 2024
- Work continued on backend labor estimates for specific service components. Currently under review by IQSS leadership.

**Comment by sbarbosadataverse** [comment]
## Status: September 2024
- Bertarelli is interested in 10TB of storage to NESE disk
- related issue: https://github.com/IQSS/dataverse.harvard.edu/issues/305

**Comment by cmbz** [comment]
## Status: October 2024
- Quote was prepared for Bertarelli Collections, standard pricing

**Comment by cmbz** [comment]
## Status: November 2024
- Pending

**Comment by sbarbosadataverse** [comment]
## Status: December 2024

- Initiated [Bertarelli](https://github.com/IQSS/dataverse-HDV-Curation/issues/582) large data collection support

**Comment by cmbz** [comment]
The pilot is now concluded. Please see remaining action items and large data updates here: https://github.com/IQSS/dataverse-pm/issues/268
