### ISSUE TITLE
Epic: GREI Training Collaboration - Carpentries Task Group

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#187]
## Overview
This collaboration between GREI and The Carpentries Collaboration aims to explore opportunities for generalist repositories and data management best practices to be referenced and used in [The Carpentries’](https://carpentries.org/index.html) training programs. The goal is to enhance the skills of researchers and librarians in data and software management and sharing, ensuring high-quality deposits into GREI repositories, with a focus on biomedical research community needs.

Note: This project is a supplement to Harvard's main NIH GREI grant.

## Preliminary Tasks
- [x] Complete SOW
- [x] Ishwar and NIH approved
- [x] Submit SOW to Brooke for review
- [x] Collect subcontract information for Brooke
- [x] Submit Emily Katz responsibilities to Brooke
- [x] Await final SOW submission from Brooke

## Related
- https://github.com/IQSS/dataverse-pm/issues/234

## Resources
- [Statement of Work](https://docs.google.com/document/d/1NG2Dxwcfe1wdTR6rrxiz6KlzczMgy_16/edit?usp=sharing&ouid=102516728224230315414&rtpof=true&sd=true)

**Comment by cmbz** [comment]
## January 2024

- The "Training Collaboration - Carpentries Task Group" met in November and decided on two task group outputs for Year 2: 1. discuss collaboration opportunities with Carpentries team members (outreach about data sharing and archiving, module development and maintenance, etc.), and 2. identify gaps in Carpentries lesson modules and opportunities for future content development in Year 3.

**Comment by cmbz** [comment]
## Status: March 2024
- Katie stepped down from the Task Group in March. 
- A discussion about staffing and whether IQSS will host supplement is needed to proceed.

**Comment by cmbz** [comment]
## Status: April 2024
-

**Comment by cmbz** [comment]
## Status: May 2024
- Pending

**Comment by cmbz** [comment]
## Status: June 2024
- Pending

**Comment by cmbz** [comment]
## Status: July 2024
- Pending

**Comment by cmbz** [comment]
## Status: August 2024
- Pending

**Comment by cmbz** [comment]
## Status: September 2024
- Pending

**Comment by cmbz** [comment]
## Status: October 2024
- Pending

**Comment by sbarbosadataverse** [comment]
## Status: November 2024
 - The Carpentries Unit has been added to the Year 4 GREI plan, waiting on confirmation of their tasks and deliverables. I requested a meeting with Steve and John, and Emily is working to DRAFT their tasks and deliverables based on their SOW.
 - We have a plan for monthly reporting on their progress.

**Comment by sbarbosadataverse** [comment]
## Status: January 2025
1st invoice was received and forwarded to Brooke, who had further comments on %allocation.

**Comment by cmbz** [comment]
**2025/01/16**
- Now that the project/supplement has started, I am closing this issue and instead we will make all future status updates here: https://github.com/IQSS/dataverse-pm/issues/234
- The Carpentries supplement work will also be reported on the Harvard monthly reports to NIH.
