### ISSUE TITLE
Epic: Extend and Enhance Support for PIDs

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#195]
## Overview 
This epic was created to track work towards the goal of making deposits in Dataverse repositories more FAIR by increasing the number of PIDs in deposit metadata, such as the number of ORCIDs and RORs, and evaluating and improving how Dataverse repositories use PIDs to help users find and make sense of deposits.

## Related Issues
- [x] https://github.com/IQSS/dataverse-pm/issues/19
- [x] https://github.com/IQSS/dataverse/issues/9370
- [x] https://github.com/IQSS/dataverse/issues/9151
- [x] https://github.com/IQSS/dataverse/issues/10460
- [ ] https://github.com/IQSS/dataverse-pm/issues/127
- [ ] https://github.com/IQSS/dataverse-pm/issues/117

**Comment by cmbz** [comment]
## Status: August 2024
- See update: https://github.com/IQSS/dataverse-pm/issues/19#issuecomment-2297013508

**Comment by jggautier** [comment]
@cmbz I took a stab at adding an overview for this GitHub issue.

I'd like to also update this epic GitHub issue to indicate what's been done so far to increase support of PIDs in deposit metadata, how well that's been working, and potential next steps informed by the usability testing and benchmarking we've been discussing in the metadata coordination group. Maybe that would involve just pointing to the other GitHub issues, like https://github.com/IQSS/dataverse-pm/issues/356, and updates in those issues, like https://github.com/IQSS/dataverse-pm/issues/127#issuecomment-2899191985.

I didn't include anything about Handles since I haven't been involved in that work. I wrote at https://github.com/IQSS/dataverse-pm/issues/19#issuecomment-2297430833 that goals involving Handles might include having Dataverse repositories being able to register PIDs for dataset versions, which is described in the GitHub issue at https://github.com/IQSS/dataverse/issues/4499 and the PR at https://github.com/IQSS/dataverse/pull/9462.

Would it be possible to remove mention of Handles from this epic?

**Comment by cmbz** [comment]
@jggautier sounds good, thanks. Please edit the contents and scope of this epic as you see fit.
