### ISSUE TITLE
Epic: Analyze current DP Creator settings and develop a Python script to automatically generate inputs

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#213]
## Overview
- Develop a program that generates a Python script based on user inputs to DP Creator. A user may download/use this script to generate a DP Release on their laptop or in a secure environment.
  - Originally conceived as an output from DP Creator. 
- This program is being developed in a new GitHub repository:
   - https://github.com/opendp/dpcreator-script-maker
- Note that it may be possible to reuse this script in the context of updating the OpenDP library version

## Participants
- @raprasad 

## Tasks

- [x] Create new GitHub repo
  - [x] https://github.com/opendp/dpcreator-script-maker
- [x] Analyze current DP creator settings
- [x] Develop and test Python script

## Resources
- https://github.com/opendp/dpcreator-script-maker
- https://github.com/IQSS/dataverse-pm/issues/212

**Comment by cmbz** [comment]
2024/06/06
- Closing as complete

**Comment by raprasad** [comment]
## Status: June 2024
- Inactive development in June.
- Script development is dependent on OpenDP Library update to version 0.10 which includes significant API changes as well as the use of the Polars DataFrame.
  - [OpenDP Library 0.10 was released on June 24, 2024](https://opendp.org/blog/announcing-opendp-library-010)
- Development to resume the week of July 8, 2024 and will include @mccalluc
