### ISSUE TITLE
Epic: Design and implement a simplified, easy-to-deploy, and containerized version of DP Creator

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#215]
## Overview
-  Design and implement a simplified, easy-to-deploy, and containerized version of DP Creator

## Particpants
- @raprasad 
- @pdurbin 
- @mccalluc

## Tasks
- [ ] **Consult with Phil Durbin to discuss possibilities and identify additional needs**. Topics include: authentication, organization of the code
- [ ] **Design approach with input from consultation**. 
  - Note: Ellen has a preliminary proposal involving using a script to deploy all components in a local environment for how a simple turnkey app could be created
  - Note: Images currently exist on Azure (as per Raman's comment). Images are older (2023) but may be workable
- [ ] Implement and test the approach 
- [ ] Develop user documentation for deploying the single app

## Resources
- https://github.com/IQSS/dataverse-pm/issues/212

**Comment by cmbz** [comment]
## Status: October 2024
- Closing. Replaced by new project: https://github.com/IQSS/dataverse-pm/issues/331
