### ISSUE TITLE
Task: Evaluate and implement biomedical metadata blocks from DANS on HDV

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#232]
## Overview
- Evaluate [biomedical metadata blocks created by DANS](https://groups.google.com/g/dataverse-community/c/5tZNXxyYjyA/m/r1htF6d3BQAJ)
- Decide whether it is appropriate to install on Harvard Dataverse Repository
- Install and test metadata blocks, if so.

### Part 1:
- [x] Connect with DANS team (Slava, Laura, Cees) to demonstrate their blocks
- [ ] Community discussion to  evaluate and determine which DANS blocks will be useful (involved GREI members from Mendeley)

### Part 2
- [ ] Any blockers to adding the blocks to Demo
- [ ] Add to demo website 
- [ ] Invite community (in collab with Julie at countway) to test and provide feedback in this issue, or create a feedback issue to track feedback in
- [ ] We can wait and see if GREI is extended before adding to production

## Resources
- [Google Group post](https://groups.google.com/g/dataverse-community/c/5tZNXxyYjyA/m/r1htF6d3BQAJ)

**Comment by cmbz** [comment]
2025-04-7
- Add back to GREI 2 as a Year 4 task

**Comment by sbarbosadataverse** [comment]
Met with Julian on 07/01/2025 and discussed an update to the tasks list above, including inviting additional metadata experts/interest groups to attend any demo we schedule. We can invite Ted Haberman, as he may have an interest in the metadata export options of these blocks. We will include Julie (Countway) and any members of that community with an interest, as well as reach out to the GREI metadata task group in case they have an interest in the demo and testing. Ishwar may also have NIH folks with an interest. SB will make the initial connections with DANS to schedule the demo.
