### ISSUE TITLE
GREI 2: Task 1 - Propose redesigns of citation metadata block and use and build on controlled vocabulary functionality in order to improve the collection and use of metadata about people and organizations associated with deposits, including use of ROR and ORCID (Sketch stage)

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse-pm#258]
## Purpose
- Ensure that we consider a broad range of ideas for improving how Dataverse collects and uses metadata about people and organizations associated with deposits
- Further improve our shared understanding of goals, requirements, opportunities and constraints by seeing the solutions that come from our individual understanding

## Background
- This is the third stage of a design sprint that the The Dataverse UX Working Group is using in order to implement a solution for improving the collection and use of metadata about people and organizations associated with deposits in a way that encourages a shared understanding of goals and more community collaboration around decision making, and prioritizes testing and evaluation by scaling our ability to distribute more of that work.

## Participants
- Lead: Julian Gautier
- Sherry Lake
- Dieuwertje Bloemen

## Resources
- [Rationale for design sprints and plan for design sprint about using ROR and ORCID to improve metadata about people and organizations associated with deposits](https://docs.google.com/document/d/1P39-FzbUXq7kvcLUGko4tCx1k6SS_HqJ1bM6MPrSy8A)
- [Schedule for design sprint for improving metadata about people and organizations](https://docs.google.com/spreadsheets/d/1qbJiMWtWUxMFAGz6kl96sET1UBmvZiPigpNHz1UzQuI)
- [Design Sprint Kit](https://designsprintkit.withgoogle.com)

## Timeline
- Start: 2024-08-12
- Milestone: Participants add sketches and other design artifacts someplace where other participants can see them
- End: 2024-08-16

## Tasks
- [ ] Participants review how others, such as those working on other data repositories, have addressed similar goals and challenges
- [x] Participants may meet virtually to discuss tips for generating ideas that can be shared
- [ ] Participants generate ideas individually, such as through sketches

**Comment by jggautier** [comment]
## Status: June 2024
- Members of the Dataverse UX WG started planning for how to share design ideas. See [agenda and notes for the 2024-06-27 meeting](https://docs.google.com/document/d/1Ir5IcqCSdzlBGLZA_Ruh6CpR8JsUgEK5bpg-UBgmWlo/edit#bookmark=id.jrj2urq560la).

**Comment by jggautier** [comment]
## Status: July 2024
-

**Comment by jggautier** [comment]
## Status: August 2024
-
