### ISSUE TITLE
GREI 2: Task 1 - Review proposed redesigns of the citation metadata block and the use and possible adjustment of the controlled vocabulary functionality for improving the collection and use of metadata about people and organizations associated with deposits (Decide stage)

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse-pm#259]
## Purpose
- Ensure that we consider a broad range of ideas for improving how Dataverse collects and uses metadata about people and organizations associated with deposits
- Further improve our shared understanding of goals, requirements, opportunities and constraints by discussing the solutions that come from our individual understanding

## Background
- This is the fourth stage of a design sprint that the The Dataverse UX Working Group is using in order to implement a solution for improving the collection and use of metadata about people and organizations associated with deposits in a way that encourages a shared understanding of goals and more community collaboration around decision making, and prioritizes testing and evaluation by scaling our ability to distribute more of that work.

## Participants
- Lead: Julian Gautier
- Sherry Lake
- Dieuwertje Bloemen

## Resources
- [Rationale for design sprints and plan for design sprint about using ROR and ORCID to improve metadata about people and organizations associated with deposits](https://docs.google.com/document/d/1P39-FzbUXq7kvcLUGko4tCx1k6SS_HqJ1bM6MPrSy8A)
- [Schedule for design sprint for improving metadata about people and organizations](https://docs.google.com/spreadsheets/d/1qbJiMWtWUxMFAGz6kl96sET1UBmvZiPigpNHz1UzQuI)
- [Design Sprint Kit](https://designsprintkit.withgoogle.com)

## Timeline
- Start: 2024-07-08
- End: 2024-07-12

## Tasks
- [ ] Participants review the solutions that other participants have shared
- [ ] Participants meet to discuss each other's solutions
- [ ] WG lead, developer create artifact for candidate design, which will be used for testing

**Comment by jggautier** [comment]
## Status: August 2024
- Members of the WG met twice in late August to review of the goals, measurable outcomes, and high-level requirements of the design sprint for improving how depositors describe people and organizations that are associated with deposits. And they started the "Decide" stage of the sprint, where they're reviewing the proposals worked on during the "Sketch" stage. See [the design sprint schedule](https://docs.google.com/spreadsheets/d/1qbJiMWtWUxMFAGz6kl96sET1UBmvZiPigpNHz1UzQuI).
- During the "Decide" stage meetings, the group agreed to move forward with several design aspects and learned that more time is needed to finish discussing the design proposals and possibly adjust the scope and high level requirements of the design sprint. The group is postponing the sprint's next stage, "Prototyping", and @jggautier extended the "Decide" stage another week so that he can review and share a summary of the group's discussions so far, so that the group can continue reviewing proposals in order to decide on a candidate design, and so that if it needs to adjust the scope and high level requirements of the design sprint, the group can follow up with other stakeholders in the Dataverse community about it.

**Comment by cmbz** [comment]
## Status: September 2024
- Pending

**Comment by jggautier** [comment]
## Status: October 2024
- Members of the working group met to prepare its proposal for improving how depositors describe people and organizations that are associated with deposits, and @jggautier began scheduling a meeting with the IQSS team to review the technical feasibility of the proposal

**Comment by jggautier** [comment]
## Status: November 2024
-
