### ISSUE TITLE
Sprint: FY25 Sprint 1 (2024-07-03 - 2024-07-17)

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#274]
## Overview
- Tracking issue for FY25 Sprint 1 planning 
- [Sprint Planning Board](https://github.com/orgs/IQSS/projects/34/views/28)

## Tasks
- [ ] Sprint end snapshot
- [ ] Establish priorities
- [ ] Resize orphaned issues & PRs
- [ ] Update labels
- [ ] Size issues in [_Needs Sizing_](https://github.com/orgs/IQSS/projects/34/views/28)
- [ ] Establish the sprint
- [ ] Sprint start snapshot

## Release
- Release [6.4](https://github.com/IQSS/dataverse/milestone/114)
