### ISSUE TITLE
Dataverse become a Local Context affiliated service provider (SB)

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse-pm#322]
## Objective:
Become Integration partners

## Resources:
 https://localcontextshub.org/integration-partners/notices/12/

## Tasks:
- [x] Membership is free for 2025 and 2026
- [x] create page on local context [hub](https://localcontextshub.org/integration-partners/notices/12/)
- [ ] create documentation on [DV guide](https://dataverse-guide--11904.org.readthedocs.build/en/11904/installation/localcontexts.html)
- [ ] Develop collection level managed workflow for use of labels and notices on HDV

## Lead:
Sonia, Jim

## Contacts
[Ashley Rojas ](ashley.rojas@localcontexts.org)

**Comment by sbarbosadataverse** [comment]
## 2025 April
-Open questions
1. Was this intended by LC to be a software-level integration or per installation?
2. Discuss managed workflow at the collection level with Jim Myers and Ashley

**Comment by cmbz** [comment]
## Status: May 2025
- Pending
