### ISSUE TITLE
Epic: QA/QC Task Group

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#346]
## Overview
- Task group to perform comprehensive review of how QA/QC is performed at GREI repositories

## Related
- https://github.com/NIH-GREI/grei-pm/issues/134

**Comment by sbarbosadataverse** [comment]
## Status: November 2024
(QA/QC and Sensitive data merged into one task group, keeping indiv Git Issues)
- 1st combined group meeting completed. The SOPs were completed, reviewed, and updated. Next meeting on 12/4
-**Action items** pending: 
- [ ] Send an email to repositories (asap) asking them:
- [ ] Define QA/QC and Sensitive data for their repo
- [ ] Provide a list of QA/QC/Sensitive data tasks they employ as part of their stewardship processes

**Comment by sbarbosadataverse** [comment]
##Status: December 2024
QA/QC & Sensitive Data - ALL REPOS: Please add your repo’s responses to the [QA/QC & Sensitive Data Questionnaire](https://docs.google.com/spreadsheets/d/14gX4PRjFKqYbIeM7DiRITFdxLsR0377_TQGz-wgn7pI/edit?usp=sharing) by Wednesday Dec. 18.

**Comment by sbarbosadataverse** [comment]
## Status: January 2025
[Completed QA/QC and Sensitive Data survey for HDV](urlhttps://docs.google.com/spreadsheets/d/14gX4PRjFKqYbIeM7DiRITFdxLsR0377_TQGz-wgn7pI/edit?gid=0#gid=0)

**Comment by cmbz** [comment]
## Status: February 2025
- Pending

**Comment by cmbz** [comment]
## Status: March 2025
- Pending
