### ISSUE TITLE
Project: Migrate dataverse.org website to GitHub Pages

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse-pm#349]
## Overview
- The dataverse.org website is currently hosted on Open Scholar. Harvard will no longer support Open Scholar sites and is moving to Drupal.
- Rather than migrated dataverse.org to Drupal, we plan to migrate instead to [GitHub Pages](https://pages.github.com/).

### Rationale
- The [GDCC website](https://www.gdcc.io/index.html) (formerly on Open Scholar) is now hosted on GitHub. The move has been popular. GitHub hosting provides greater visibility and Community engagement. For example, it makes it easy for site owners to make updates and offers Community users the opportunity to [contribute site improvements](https://github.com/gdcc/www.gdcc.io/pulls?q=is%3Apr+is%3Aclosed) (e.g., fix typos, broken links) that are then approved or denied by site owners.
- Currently, our [dataverse.org](http://dataverse.org/) site has minimal static content and links to other resources, like our [Guides](https://guides.dataverse.org/en/latest/) and [metrics](https://dataverse.org/metrics), so a migration to GitHub Pages won't be very difficult or time consuming. 
- Moving to [GitHub Pages](https://pages.github.com/) will boost Dataverse project visibility and strengthen our ties within the Open Source ecosystem. 
- [GitHub Pages](https://pages.github.com/) supports [Markdown](https://www.markdownguide.org/), which is a common, easy-to-use formatting language
- We will use site design approaches and tools to ensure user accessibility.

## Tasks

- [ ] Move CoreTrustSeal Guide to the guides site
- [x] Create GitHub Pages site
  - [ ] Create a GitHub Action to publish the site, possibly modeled off [the GDCC one](https://github.com/gdcc/www.gdcc.io/blob/main/.github/workflows/static.yml).
- [x] Create site [information architecture](https://docs.google.com/document/d/1x4FeqWMb8fPs7Q71uaIlfdg8_rdexx0oa1DzxAZ_4mk/edit?usp=sharing)
- [ ] Consider moving presentations and publications to zenodo or OSF
- [ ] Consider moving DataverseTV into the site
- [ ]  Identify compatible accessibility assessment tools (see: [Getting started with accessibility](https://huit.harvard.edu/news/getting-started-accessibility) and [Automated Tools for Testing Accessibility | Digital Accessibility](https://accessibility.huit.harvard.edu/auto-tools-testing#siteimprove)

## Resources
- sphinx.dataverse.org repository: "This GitHub project hosts the sources from which the Dataverse website at https://sphinx.dataverse.org/ is built. If we like Sphinx, we might switch https://dataverse.org/ to it. Builds are automated and any commited changes will be released by automation." https://github.com/IQSS/sphinx.dataverse.org
- Site under development: https://sphinx.dataverse.org
- [dataverse.org on GitHub information architecture](https://docs.google.com/document/d/1x4FeqWMb8fPs7Q71uaIlfdg8_rdexx0oa1DzxAZ_4mk/edit?usp=sharing) Google doc
- [Zulip discussion](https://dataverse.zulipchat.com/#narrow/channel/375707-community/topic/move.20dataverse.2Eorg.20to.20GitHub.3F/near/478947917)
- [dataverse.org on GitHub information architecture and static site generator bakeoff](https://docs.google.com/document/d/1x4FeqWMb8fPs7Q71uaIlfdg8_rdexx0oa1DzxAZ_4mk/edit?usp=sharing)

**Comment by cmbz** [comment]
## Status: November
- Created tracking issue
- Began to identify necessary tasks

**Comment by cmbz** [comment]
## Status: December 2025
- Sonia, Dwayne, Phil, and Ceilyn met to discuss strategies and next steps for dataverse.org
- Challenges
  - Current dataverse.org has a tremendous amount of content. Migrating the content in a programmatic way to another platform will likely require support from HWP 
  - The GitHub Pages themes we know about don't have very pleasing designs
  - GitHub Pages requires skill working with Git, and not all members of the dataverse.org maintainers currently have this skill
- Decision
  - Leverage the best aspects of the Drupal and GitHub platforms. For high-impact content (e.g., homepage) that requires attractive desing, use Drupal. For content that is code-related, or may see Community-updates, and/or duplicated in other places (e.g., dataverse GitHub repo), use GitHub.
  - We will stick with the Drupal platform
  - We want a nicer dataverse.org homepage
    - Dwayne will start with implementing his redesigned homepage
  - Which dataverse.org pages would be better placed in the Dataverse Guides?
    - Integrations (already there)
    - Features. See this issue: https://github.com/IQSS/dataverse/issues/11998
    - GDCC/Community-Related Content (may leverage the upcoming GDCC playbook that is under development)
      - Working Groups (already on GDCC website)
      - Community Calls (move to GDCC?)
      - Events (move to GDCC?)
      - DataverseTV (?)
    - Map/List of installations (?)

**Comment by cmbz** [comment]
Now that we've made our decision, I'm closing this issue. Work will continue here: https://github.com/IQSS/dataverse-pm/issues/498
